# Request
float32 target_x  # 狙う場所のX座標 (mm)
float32 target_y  # 狙う場所のY座標 (mm) 奥方向
float32 height_z  # 狙う高さ (mm) ネット越えなら高く、バウンド狙いなら0
string speed_mode # "fast", "normal", "slow"

---
# Response
bool success
string message